// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://munsnxkjycbmbrrskvpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11bnNueGtqeWNibWJycnNrdnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODM5MjUsImV4cCI6MjA2NzA1OTkyNX0.Ow5nr8p3GV2uKMX6fJNHJ5YMKN0-W4UZoF4uMjSRFjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});